apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-minecraft-
  namespace: argo
spec:
  entrypoint: hardwired-artifact
  templates:
    - name: hardwired-artifact
      inputs:
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://github.com/Hnatekmar/minecraft-server.git
      container:
        image: docker:19.03.13
        command: [sh, -c]
        args: ["sleep 5 && cd /src/minecraft && docker build . -t registry.lan/minecraft"]
        env:
          - name: DOCKER_HOST               # the docker daemon can be access on the standard port on localhost
            value: 127.0.0.1
      sidecars:
        - name: dind
          image: docker:dind          # Docker already provides an image for running a Docker daemon
          args:
            - "--insecure-registry=http://registry.lan"
          env:
            - name: DOCKER_TLS_CERTDIR         # Docker TLS env config
              value: ""
          securityContext:
            privileged: true
          mirrorVolumeMounts: true