apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-claim
  labels:
    app: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  labels:
    app: minecraft
spec:
  replicas: 1
  template:
    metadata:
      name: minecraft
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: registry.lan/minecraft
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /server/world
              name: world
      restartPolicy: Always
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: minecraft-claim
  selector:
    matchLabels:
      app: minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  selector:
    app: minecraft
  ports:
    - port: 25565
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
    - host: "minecraft.lan"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minecraft-service
                port:
                  number: 25565