apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  template:
    metadata:
      name: minecraft
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: registry.lan/minecraft
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: minecraft

