FROM ubuntu:20.04

#ENV SERVER_URL="https://www.curseforge.com/minecraft/modpacks/ftb-presents-direwolf20-1-12/download/2690320/file"
#
#RUN apt-get update && \
#    apt-get install -y wget openjdk-11-jdk unzip && \
#    apt-get clean

WORKDIR /server

#RUN wget ${SERVER_URL}
#
#RUN unzip *.zip

CMD watch "sleep 1"